export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'
export const USERNAME_CHANGED='USERNAME_CHANGED';
export const PASSWORD_CHANGED='PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL';
export const LOGIN_USER='LOGIN_USER';
export const SELECTED_SUMMARY='SELECTED_SUMMARY';